version: 0.2

phases:
  install:
    commands:
      - echo Install phase started
      - apt-get update -y
      - su
      - apt-get install sudo

  build:
    commands:
      - echo Build phase started
#       - git clone https://github.com/dashkun1215/KNOV-2813.git
      - pwd
      - aws --version
#       - cd ./KNOV-2813
#       - $(aws ecr get-login --no-include-email)
      - docker login -u AWS -p $(aws ecr get-login-password --region eu-west-1) 672671632666.dkr.ecr.eu-west-1.amazonaws.com
#       - aws ecr get-login-password --region eu-west-1 672671632666.dkr.ecr.eu-west-1.amazonaws.com
#       | docker login --username AWS --password-stdin 
      - sudo docker build -t knov-2813 .
      - sudo docker tag knov-2813:latest 672671632666.dkr.ecr.eu-west-1.amazonaws.com/knov-2813:latest
      - sudo docker push 672671632666.dkr.ecr.eu-west-1.amazonaws.com/knov-2813:latest
