AWSTemplateFormatVersion: 2010-09-09
Description: >
  pipeline and task for KNOV-2813
Parameters:
  AccountType:
    Description: The type of the account.
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - qa
      - stage
      - prod
  ProjectName:
    Type: String
    Description: knovio-infrastructure project name
    Default: knov-2813-pipe
  GitHubTocken:
    Type: String


Resources:
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub Daryna-${AccountType}-${ProjectName}-knov-2813-project-${AWS::Region}
      Description: "Project for KNOV-2813"
      BadgeEnabled: false
      QueuedTimeoutInMinutes: 10
      TimeoutInMinutes: 15
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        ImagePullCredentialsType: CODEBUILD
        PrivilegedMode: true
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.yaml
      ServiceRole: !ImportValue knov:2813:ServiceRole
      LogsConfig:
        CloudWatchLogs:
          GroupName: !ImportValue knov:2813:LogGroup
          Status: ENABLED

  CodeDeployProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub Daryna-${AccountType}-${ProjectName}-templates-deploy-project-${AWS::Region}
      Description: !Sub "${ProjectName} templates deploy CodeBuild project for CodePipeline"
      BadgeEnabled: false
      QueuedTimeoutInMinutes: 10
      TimeoutInMinutes: 45
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:3.0
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.yaml
      ServiceRole: !ImportValue knov:2813:ServiceRole
      LogsConfig:
        CloudWatchLogs:
          GroupName: !ImportValue knov:2813:LogGroup
          Status: ENABLED

  # Pipeline
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub ${AccountType}-knov-2813-cfn
      RoleArn: !ImportValue knov:2813:PipelineRole
      ArtifactStore:
        Type: S3
        Location: !ImportValue knov:2813:CodePipelineBucket
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              InputArtifacts: [ ]
              Namespace: "SourceVariables"
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: "1"
                Provider: GitHub
              OutputArtifacts:
                - Name: SourceArtifact
              Configuration:
                Owner: "dashkun1215"
                Branch: master
                Repo: KNOV-2813
                OAuthToken: !Ref "GitHubTocken"
                PollForSourceChanges: false
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: Validation
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: BuildArtifact
              Configuration:
                ProjectName: !Ref CodeBuildProject
              RunOrder: 1
        - Name: Deploy
          Actions:
            - Name: Deploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: ECS
                Version: "1"
              InputArtifacts:
                - Name: BuildArtifact
              Configuration:
                ClusterName: !ImportValue knov:2813:ClusterECS
                ServiceName: !ImportValue knov:2813:ServiceECS