AWSTemplateFormatVersion: 2010-09-09
Description: >
  training task KNOV-2813
Parameters:
  AccountType:
    Description: The type of the account.
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - qa
      - stage
      - prod
  ProjectName:
    Type: String
    Description: knovio-infrastructure project name
    Default: knov-2813-cfn

Resources:
  # ECR repositories
  EcrRepository:
    Type: AWS::ECR::Repository
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      RepositoryName: !Sub ${AccountType}-knov-2813-cfn

  #CodePipelineBucket
  CodePipelineBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub ${AccountType}-${ProjectName}-${AWS::Region}-${AWS::AccountId}
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: Remove incomplete multipart uploads
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 2
            Status: Enabled
          - Id: Remove old packages
            ExpirationInDays: 5
            Status: Enabled
            Prefix: !Sub codepipeline/${ProjectName}
          - Id: !Sub Remove old ${ProjectName} deploy packages
            ExpirationInDays: 5
            Status: Enabled
            Prefix: !Sub codebuild/${ProjectName}/
          - Id: Remove old versions
            NoncurrentVersionExpirationInDays: 5
            Status: Enabled

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub Daryna-${AccountType}-${ProjectName}-knov-2813-project-${AWS::Region}
      Description: "Project for KNOV-2813"
      BadgeEnabled: false
      QueuedTimeoutInMinutes: 10
      TimeoutInMinutes: 15
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        ImagePullCredentialsType: CODEBUILD
        PrivilegedMode: true
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.yaml
      ServiceRole: !Ref ServiceRole
      LogsConfig:
        CloudWatchLogs:
          GroupName: !Ref LogGroup
          Status: ENABLED

  CodeDeployProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub Daryna-${AccountType}-${ProjectName}-templates-deploy-project-${AWS::Region}
      Description: !Sub "${ProjectName} templates deploy CodeBuild project for CodePipeline"
      BadgeEnabled: false
      QueuedTimeoutInMinutes: 10
      TimeoutInMinutes: 45
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:3.0
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.yaml
      ServiceRole: !Ref ServiceRole
      LogsConfig:
        CloudWatchLogs:
          GroupName: !Ref LogGroup
          Status: ENABLED

  ClusterECS:
    Type: AWS::ECS::Cluster
    Properties:
      CapacityProviders:
        - FARGATE
      ClusterName: !Sub ${AccountType}-knov-2813-cfn

  # CloudWatch Log Group
  LogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      RetentionInDays: 7
      LogGroupName: !Sub ${AccountType}-knov-2813-cfn

  #Roles
  ServiceRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - !Ref ECRPolicy
        - !Ref CodeBuildBasePolicy
        - !Ref CloudWatchLogsPolicy
        - !Ref ECSPolicy
        - !Ref IAMPolicy
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
                - codebuild.amazonaws.com
            Action: sts:AssumeRole


  PipelineRole:
    Type: AWS::IAM::Role
    DeletionPolicy: Delete
    Properties:
      ManagedPolicyArns:
        - !Ref AWSCodePipelineServiceRolePolicy
        - !Ref CloudWatchLogsPolicy
        - !Ref ECSPolicy
        - !Ref CodeBuildBasePolicy
        - !Ref IAMPolicy
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
          - Effect: Allow
            Principal:
              Service:
              - codepipeline.amazonaws.com
              - codebuild.amazonaws.com
            Action: sts:AssumeRole

  #Policies

  ECRPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: 2813-ECR-policy
      Description: !Sub "${ProjectName} ECR creation"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - ecr:DescribeImages
              - ecr:GetAuthorizationToken
              - ecr:BatchCheckLayerAvailability
              - ecr:CompleteLayerUpload
              - ecr:UploadLayerPart
              - ecr:InitiateLayerUpload
              - ecr:PutImage
            Effect: Allow
            Resource:
              - !GetAtt EcrRepository.Arn
          - Action:
              - ecr:GetAuthorizationToken
            Effect: Allow
            Resource: '*'

  ECSPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: 2813-ECS-policy
      Description: !Sub "${ProjectName} ECS creation"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - ecs:Update*
              - ecs:Create*
              - ecs:RunTask
              - ecs:Start*
              - ecs:StopTask
              - ecs:Delete*
            Resource:
              - !Sub arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:service/${AccountType}*
              - !Sub arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:task-definition/${AccountType}*
              - !GetAtt ClusterECS.Arn
              - !Sub arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:task-set/${AccountType}*
              - !Sub arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:container-instance/${AccountType}*
          - Action:
              - ecs:CreateTaskSet
              - ecs:Register*
              - ecs:Deregister*
              - ecs:Describe*
              - ecs:List*
            Effect: Allow
            Resource:
              - "*"

  IAMPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: 2813-IAM-policy
      Description: !Sub "${ProjectName} ECS creation"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - iam:PassRole
            Effect: Allow
            Resource:
              - "*"

  CloudWatchLogsPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: 2813-CloudWatchLogs-policy
      Description: !Sub "${ProjectName} CloudWatch"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Resource:
              - !GetAtt LogGroup.Arn
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents

  AWSCodePipelineServiceRolePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: 2813-AWSCodePipelineServiceRolePolicy-policy
      Description: !Sub "${ProjectName} for pipeline"
      PolicyDocument:
        Statement:
          - Action:
              - codedeploy:CreateDeployment
              - codedeploy:GetApplication
              - codedeploy:GetApplicationRevision
              - codedeploy:GetDeployment
              - codedeploy:GetDeploymentConfig
              - codedeploy:RegisterApplicationRevision
            Resource: !Sub "arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:*/Daryna*"
            Effect: Allow
          - Action:
              - cloudformation:CreateStack
              - cloudformation:DeleteStack
              - cloudformation:DescribeStacks
              - cloudformation:UpdateStack
              - cloudformation:CreateChangeSet
              - cloudformation:DeleteChangeSet
              - cloudformation:DescribeChangeSet
              - cloudformation:ExecuteChangeSet
              - cloudformation:SetStackPolicy
              - cloudformation:ValidateTemplate
            Resource:
              - !Sub arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/*
            Effect: Allow
          - Action:
            - codebuild:BatchGetBuilds
            - codebuild:StartBuild
            - codebuild:BatchGetBuildBatches
            - codebuild:StartBuildBatch
            - codepipeline:*
            - codedeploy:CreateDeployment
            - codedeploy:GetApplication
            - codedeploy:GetApplicationRevision
            - codedeploy:GetDeployment
            - codedeploy:GetDeploymentConfig
            - codedeploy:RegisterApplicationRevision
            - codestar-connections:UseConnection
            Resource:
              - !Sub "arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:*/Daryna*"
            Effect: Allow
          - Effect: Allow
            Action:
              - cloudformation:ValidateTemplate
            Resource:
              - !Sub arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/*
        Version: '2012-10-17'


  CodeBuildBasePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: 2813-CodeBuild-policy
      Description: !Sub "${ProjectName} CodeBuild"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Resource:
              - !GetAtt CodePipelineBucket.Arn
              - !Sub
                - ${CodePipelineBucketArn}/*
                - CodePipelineBucketArn: !GetAtt CodePipelineBucket.Arn
            Action:
              - s3:Put*
              - s3:CreateBucket
              - s3:Get*
              - s3:DeleteBucket
              - s3:ListBucket
          - Effect: Allow
            Action:
              - codebuild:*
              - codebuild:CreateReportGroup
              - codebuild:CreateReport
              - codebuild:UpdateReport
              - codebuild:BatchPutTestCases
              - codebuild:BatchPutCodeCoverages
              - codebuild:BatchGetBuilds
              - codebuild:StartBuild
              - codebuild:BatchGetBuildBatches
              - codebuild:StartBuildBatch
              - codepipeline:*
              - codedeploy:CreateDeployment
              - codedeploy:Get*
              - codedeploy:RegisterApplicationRevision
              - codestar-connections:UseConnection
            Resource:
              - !Sub "arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:project/Daryna-*"

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ExecutionRoleArn: arn:aws:iam::672671632666:role/ecsTaskExecutionRole
      Cpu: '256'
      Family: KNOV-2813
      Memory: '512'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ContainerDefinitions:
        - Name: !Sub ${AccountType}-${AWS::AccountId}-knov-2813cfn-${AWS::Region}
          Image: alpine:3.4
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: eu-west-1
              awslogs-stream-prefix: ecs


  ServiceECS:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ClusterECS
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
      DeploymentController:
        Type: ECS
      LaunchType: FARGATE
      NetworkConfiguration:
         AwsvpcConfiguration:
           AssignPublicIp: ENABLED
           Subnets:
             - !ImportValue knov:2813:subnet:public:1
             - !ImportValue knov:2813:subnet:public:2
             - !ImportValue knov:2813:subnet:public:3
      ServiceName: !Sub ${AccountType}-2813-cfn
      TaskDefinition: !Ref TaskDefinition

Outputs:
  ServiceECS:
    Description: A reference to the ServiceECS
    Value: !Ref ServiceECS
    Export:
      Name: knov:2813:ServiceECS


  CodePipelineBucket:
    Description: A reference to the CodePipelineBucket
    Value: !Ref CodePipelineBucket
    Export:
      Name: knov:2813:CodePipelineBucket

  CodeBuildProject:
    Description: A reference to the CodeBuildProject
    Value: !Ref CodeBuildProject
    Export:
      Name: knov:2813:CodeBuildProject

  ClusterECS:
    Description: A reference to the ClusterECS
    Value: !Ref ClusterECS
    Export:
      Name: knov:2813:ClusterECS

  PipelineRole:
    Description: A reference to the PipelineRole
    Value: !GetAtt PipelineRole.Arn
    Export:
      Name: knov:2813:PipelineRole

